name: faustus
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - annotated-types
      - anyio
      - certifi
      - charset-normalizer
      - distro
      - exceptiongroup
      - filelock
      - fsspec
      - h11
      - httpcore
      - httpx
      - idna
      - jinja2
      - jiter
      - llvmlite
      - markupsafe
      - more-itertools
      - mouseinfo
      - mpmath
      - networkx
      - numba
      - numpy
      - openai
      - openai-whisper
      - pillow
      - pyaudio
      - pyautogui
      - pydantic
      - pydantic-core
      - pygetwindow
      - pymsgbox
      - pyperclip
      - pyrect
      - pyscreeze
      - pytweening
      - regex
      - requests
      - sniffio
      - speechrecognition
      - sympy
      - tiktoken
      - torch
      - tqdm
      - typing-extensions
      - urllib3
